#!/usr/bin/env bash
# Start Apache and configure it to return a page containing Hello Holberton

# Update the package list
apt-get update

# Install Apache
apt-get install -y apache2

# Start Apache service
service apache2 start

# Create an index.html file with the desired content
echo "Hello Holberton" > /var/www/html/index.html

